[package]
name = "bevy_ecs_net"
version = "0.1.0"
authors = [
    "ZoOL <zhooul@gmail.com>"
]
edition = "2021"
description = "Event based networking library for Bevy"
readme = "README.md"
repository = "https://github.com/foxzool/bevy_ecs_net"
license = "MIT OR Apache-2.0"
categories = ["game-development", "network-programming"]
autoexamples = false
resolver = "2"

[features]
default = ["udp"]
udp = []


[dependencies]
async-net = "2.0.0"
bevy = { version = "0.13.2", default-features = false, features = ["multi-threaded", ] }
bytes = "1.6.0"
dashmap = { version = "5.5.3" }
kanal = "0.1.0-pre8"
futures-lite = "2.3.0"
serde = { version = "1.0.198", features = ["derive"] }


bincode = { version = "1.3.3", optional = true }
serde_json = { version = "1.0.68", optional = true }



[[example]]
name = "udp-example"
path = "examples/udp_example.rs"
required-features = ["udp", "serde_json", "bincode"]


[[example]]
name = "udp-complex"
path = "examples/udp_complex.rs"
required-features = ["udp"]




[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
