[package]
name = "bevy_udp_com"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-net = "2.0.0"
bevy_com_shared = { path = "../shared" }
bevy = { workspace = true }